app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("user.urls"))
]

user/urls.py
from django.urls import path

from .views import UsersCreateView, UsersListView, UsersUpdateView, UsersDeleteView

urlpatterns = [
  path("", UsersListView.as_view(), name="home"),
  path("create", UsersCreateView.as_view(), name="new_user"),
  path("delete/<int:pk>", UsersDeleteView.as_view(), name="delete_user"),
  path("update/<int:pk>", UsersUpdateView.as_view(), name="update_user")
]

user/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse 

class User(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False)
    email = models.EmailField(max_length=255, null=False, blank=False)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(default=datetime.now)

    def get_absolute_url(self):
        return reverse("usuarios", args=[str(self.id)])

    def __str__(self):
        return self.name

user/forms.py
from django import forms
from django.forms import TextInput, EmailInput, PasswordInput, DateInput
from .models import User

class UserModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = "__all__"
        widgets = {
            "name": TextInput(attrs={
                "class": "form-control mt-2 w-100",
                "placeholder": "Informe o seu nome"
            }),
            "email": EmailInput(attrs={
                "class": "form-control mt-2 w-100",
                "placeholder": "Informe o seu email"
            }),
            "password": TextInput(attrs={
                "type": "password",
                "class": "form-control mt-2 w-100",
                "placeholder": "Informa a sua senha",
            }),
            "created_at": DateInput(attrs={
                "style": "display: none;",
            })
        }
        
        def clean_password(self):
            password = self.cleaned_data.get("password")
            if not password:
                self.add_error("value", "O campo da senha deve ser preenchido.")
            return password

user/views.py
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from .models import User
from .forms import UserModelForm

class UsersCreateView(SuccessMessageMixin, CreateView):
    model = User
    form_class = UserModelForm
    template_name = 'new_user.html'
    success_url = '/users/'
    success_message = "%(name)s foi criado com sucesso!"

class UsersListView(ListView):
    model = User
    template_name = 'users.html'
    context_object_name = 'usuarios'
    
    def get_queryset(self):
        users = super().get_queryset().order_by('name')
        search = self.request.GET.get('search')
        if search:
            users = users.filter(name__icontains=search)
        return users

class UsersUpdateView(SuccessMessageMixin, UpdateView):
    model = User
    form_class = UserModelForm
    template_name = 'user_update.html'
    success_url = reverse_lazy('home')
    success_message = "%(name)s foi atualizado com sucesso!"

class UsersDeleteView(SuccessMessageMixin, DeleteView):
    model = User
    template_name = 'user_delete.html'
    context_object_name = 'usuario'
    success_url = reverse_lazy('home')
    success_message = "O usuário foi deletado com sucesso!"

app/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CRUD Application</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid d-flex justify-content-between">
      <a class="navbar-brand" href="{% url 'home' %}">CRUD</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </nav>
  {% block content %}
    
  {% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

user/templates/new_user.html
{% extends "base.html" %}

{% block content %}
    <form action="" class="h-100 d-flex justify-content-center align-items-center mt-5" method="POST">
      {% csrf_token %}
      <div class="card px-4 py-3 w-50">
        <div class="card-body">
          <h5 class="card-title display-6">Cadastro de usuários</h5>
          <div class="form-group mb-3">
            <label for="id_name">Nome: </label>
            {{ form.name }}
          </div>
          <div class="form-group mb-3">
            <label for="id_email">E-mail: </label>
            {{ form.email }}
          </div>
          <div class="form-group mb-3">
            <label for="id_password">Senha: </label>
            {{ form.password }}
          </div>
          {{ form.created_at }}
          <div class="d-flex justify-content-around pt-4">
            <a href="{% url 'home' %}" class="btn btn-secondary w-25">Voltar</a>
            <input type="submit" value="Cadastrar" class="btn btn-primary w-25">
          </div>
        </div>
      </div>
    </form>
{% endblock %}

user/templates/user/users.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="jumbotron bg-dark p-5 my-4">
        <h1 class="display-4 text-white">CRUD de Usuários</h1>
        <p class="lead text-white">Uma aplicação CRUD utilizando o framework Django.</p>
        <hr class="my-4 text-white">
        <p class="text-white">Adicione</p>
        <table class="table table-dark">
            <thead>
              <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Criado em</th>
                <th scope="col">Editar</th>
                <th scope="col">Excluir</th>
              </tr>
            </thead>
            <tbody>
                {% for usuario in usuarios %}
                    <tr>
                        <th scope="row">{{usuario.id}}</th>
                        <td>{{usuario.name}}</td>
                        <td>{{usuario.email}}</td>
                        <td>{{usuario.created_at}}</td>
                        <td>
                            <a href="{% url 'update_user' usuario.id %}">
                                <button class="btn btn-primary">Editar Usuário</button>
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'delete_user' usuario.id %}">
                                <button class="btn btn-danger">Deletar Usuário</button>
                            </a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td>Não existe nenhum usuário ainda.</td>
                    </tr>
                {% endfor %}
            </tbody>
          </table>
        <a class="btn btn-success btn-lg mt-4" href="{% url 'new_user' %}" role="button">Adicionar usuário</a>
    </div>
</div>
{% endblock %}

user/templates/user_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container pt-5">
  <form class="h-100 d-flex justify-content-center align-items-center" method="post">{% csrf_token %}
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Você tem certeza que deseja deletar o usuário <span class="text-primary">{{ usuario.name }}</span>?</h5>
        <div class="d-flex justify-content-around pt-4">
          <a href="{% url 'home' %}" class="btn btn-primary">Cancelar</a>
          <input class="btn btn-danger" type="submit" value="Deletar"> 
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock %}

user/templates/user_update.html
{% extends "base.html" %}

{% block content %}
    <form class="h-100 d-flex justify-content-center align-items-center mt-5" method="POST">
      {% csrf_token %}
      <div class="card px-4 py-3 w-50">
        <div class="card-body">
          <h5 class="card-title display-6">Atualizar Usuário</h5>
          <div class="form-group mb-3">
            <label for="id_name">Nome: </label>
            {{ form.name }}
          </div>
          <div class="form-group mb-3">
            <label for="id_email">E-mail: </label>
            {{ form.email }}
          </div>
          <div class="form-group mb-3">
            <label for="id_password">Senha: </label>
            {{ form.password }}
          </div>
          {{ form.created_at }}
          <div class="d-flex justify-content-around pt-4">
            <a href="{% url 'home' %}" class="btn btn-secondary w-25">Voltar</a>
            <input type="submit" value="Atualizar" class="btn btn-primary w-25">
          </div>
        </div>
      </div>
    </form>
{% endblock %}

user/templates/users.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  {% if messages %}
    {% for message in messages %}
      {% if message.tags == "success" %}
        <div class="alert alert-success mt-4">
          {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
          {{ message }}
        </div>
      {% endif %}
    {% endfor %}
  {% endif %}

    <form class="d-flex pt-4" method="GET" action="{% url 'home' %}" role="search">
      <input class="form-control me-5" name="search" type="search" placeholder="Pesquise por um usuário." aria-label="Search">
      <button class="btn btn-outline-success btn-lg w-25" type="submit">Pesquisar</button>
    </form>
    <div class="jumbotron bg-dark p-5 my-4">
        <h1 class="display-4 text-white">CRUD de Usuários</h1>
        <p class="lead text-white">Uma aplicação CRUD utilizando o framework Django.</p>
        <hr class="my-4 text-white">
        <p class="text-white">Adicione</p>
        <table class="table table-dark">
            <thead>
              <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Criado em</th>
                <th scope="col">Editar</th>
                <th scope="col">Excluir</th>
              </tr>
            </thead>
            <tbody>
                {% for usuario in usuarios %}
                    <tr>
                        <th scope="row">{{usuario.id}}</th>
                        <td>{{usuario.name}}</td>
                        <td>{{usuario.email}}</td>
                        <td>{{usuario.created_at}}</td>
                        <td>
                            <a href="{% url 'update_user' usuario.id %}">
                                <button class="btn btn-primary">Editar Usuário</button>
                            </a>
                        </td>
                        <td>
                            <a href="{% url 'delete_user' usuario.id %}">
                                <button class="btn btn-danger">Deletar Usuário</button>
                            </a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td>Não existe nenhum usuário ainda.</td>
                    </tr>
                {% endfor %}
            </tbody>
          </table>
        <a class="btn btn-success btn-lg mt-4" href="{% url 'new_user' %}" role="button">Adicionar usuário</a>
    </div>
</div>
{% endblock %}